### ISSUE TITLE
Async json deserializing

### ISSUE THREAD

**Issue by arnaudpoullet-dkt** [haydnv/destream_json#1]
First of all thanks for sharing this crate!

I am wondering if this crate can be used for going over elements in a JSON array from an AsyncRead Stream ? In the same way that the [csv_async](https://docs.rs/csv-async/1.1.2/csv_async/) allows to go over a stream element by element as it is downloading:

```rust
#[cfg(feature = "with_serde")]
async fn filter_by_region_serde(region:&str, file_in:&str, file_out:&str) -> Result<(), Box<dyn Error>> {
    // Function reads CSV file that has column named "region" at second position (index = 1).
    // It writes to new file only rows with region equal to passed argument.
    let mut rdr = csv_async::AsyncDeserializer::from_reader(
        File::open(file_in).await?
    );
    let mut records = rdr.deserialize::<Row>();
    while let Some(record) = records.next().await {
        let record = record?;
        if record.region == region {
            println!("{:?}",record);
        }
    }
    Ok(())
}
```
Or is this not at all de purpose of this crate ?

If yes I was hoping to find an example, I have not been able to find out how to do it from the source code/documentation.

**Comment by haydnv** [comment]
Hi Arnaud, thanks for using destream_json! You can enable support for AsyncWrite using the "tokio-io" feature but there is no built-in support for AsyncRead because it's very easy to wrap an AsyncRead in a Stream using [tokio-util](https://docs.rs/tokio-util/0.6.6/tokio_util/io/struct.ReaderStream.html). Note that you can't directly deserialize into a Stream of Rows (as in your example above), so you'll have to implement FromStream and Visitor:

```rust
struct CollectionVisitor {
    value: Collection
}

#[async_trait]
impl Visitor for CollectionVisitor {
    // ...
    async fn visit_seq<A: SeqAccess>(self, mut seq: A) -> Result<Collection, A::Error> {
        // you can pass some context other than () to next_element if needed
        while let Some(row) = seq.next_element::<Row>(()).await? { 
            println!("{}", row);
            self.value.write_row(row);
        }

        Ok(value)
    }
}

struct Collection;

#[async_trait]
impl FromStream for Collection {
    type Context = ();

    async fn from_stream<D: Decoder>(_context: (), decoder: &mut D) -> Result<Collection, D::Error> {
        decoder.decode_seq(CollectionVisitor { value: Self::new() })
    }
}
```

Let me know if I'm missing something, or if you have any difficulties with this approach. I'm also open to any suggestions you have about making it more concise.

**Comment by arnaudpoullet-dkt** [comment]
Hi, thank you for your prompt reply !

I have tried implementing this with no success, for some reason how all this works is not straightforward to me. Therefore I wrote a minimum reproducible example integrating your sample code which I hope you'll be able to correct because it does not compile. I do believe this concrete example will be able to help others trying to achieve a per-element deserializing of a stream.

The only complexity I added is transforming the struct into another, because that's the point of this implementation. (Although I'm well aware that in this case I could have simply deserialized into the final struct immediately, I just kept it simple).

`Row` becomes `CountryTemp`
`Collection` becomes `Countries`
`CollectionVisitor` becomes `CountriesVisitor`

`main.rs`:

```rust
use serde::{Serialize, Deserialize};
use destream::{Visitor, Decoder, SeqAccess, FromStream};
use async_trait::async_trait;
use destream_json::decode;

#[derive(Deserialize, Debug)]
struct CountryTemp {
    name: String,
    region: String,
    #[serde(rename = "alpha2Code")]
    alpha_2_code: String,
    population: u64,
    borders: Vec<String>
}

#[derive(Serialize, Debug)]
struct Country {
    name: String,
    region: String,
}

impl From<CountryTemp> for Country {
    fn from(tmp_country: CountryTemp) -> Self {
        Country {
            name: tmp_country.name,
            region: tmp_country.region
        }
    }
}

#[async_trait]
impl FromStream for Countries {
    type Context = ();

    async fn from_stream<D: Decoder>(_context: (), decoder: &mut D) -> Result<Countries, D::Error> {
        decoder.decode_seq(
            CountriesVisitor {
                countries: Countries(Vec::new())
            }
        )
    }
}

struct Countries(Vec<Country>);

struct CountriesVisitor {
    countries: Countries
}

#[async_trait]
impl Visitor for CountriesVisitor {
    type Value = ();

    fn expecting() -> &'static str {
        "A country"
    }

    // ...
    async fn visit_seq<A: SeqAccess>(&mut self, mut seq: A) -> Result<Countries, A::Error> {
        // you can pass some context other than () to next_element if needed
        while let Some(country) = seq.next_element::<CountryTemp>(()).await? {
            println!("{:?}", country);
            //many operations/transformations can be done here
            self.countries.0.push(country.into())
        }
        //not sure what and why I'm returning something here
        Ok(self.countries)
    }
}

#[tokio::main]
async fn main() {

    let countries  = decode((),reqwest::get("https://restcountries.eu/rest/v2/all").await.unwrap().bytes_stream()).await.unwrap();
}
```

with `Cargo.toml`:
```TOML
[package]
name = "test-destream"
version = "0.1.0"
authors = ["Arnaud <arnaud.poullet>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.49"
destream = "0.3.2"
destream_json = "0.5.4"
reqwest = { version = "0.11.3", features = ["stream"] }
serde = "1.0.125"
serde_json = "1.0.64"
tokio = { version = "1.5.0", features = ["full"] }
```

Clearly I've got it all wrong because there is nowhere I'm indicating to the `decode()` method what visitor it's supposed to use. There are also general lifetime & return type issues. Do you think you could show me a working example of what I'm trying to do ? Or even pointing me in the right direction would most appreciated.

**Comment by haydnv** [comment]
The main issue here is that destream and serde are not compatible (because destream is async and serde is not, among other reasons) so the serde macros `#[derive(Deserialize, Serialize)]` don't do anything for you when you use destream. Destream is intended for situations where you need to decode a stream that's too large to fit into memory, which is why it's a little more complicated than serde. In this case you don't strictly need destream, because the values you're decoding fit entirely into memory. You could just use serde_json by first buffering the entire stream into memory.

Destream does not have macros to auto-generate `FromStream` and `ToStream` impls. One reason is that these are not very efficient at scale--for example, encoding the field names "name" and "region" over and over for every item in the list would waste a lot of bandwidth. Assuming that you do want to use destream, the first step would be to `impl FromStream for Country`:

```rust
use async_trait::async_trait;
use destream::{Decoder, FromStream};
use futures::TryFutureExt;

struct Country {
    name: String,
    region: String,
}

#[async_trait]
impl FromStream for Country {
    // `Context` allows you to pass a sink to write values to, so you don't have to keep them all in memory.
    // In this case you can use the unit context because a `Country` always resides entirely in memory.
    type Context = ();

    async fn from_stream<D: Decoder>(cxt: (), decoder: &mut D) -> Result<Self, D::Error> {
        FromStream::from_stream(cxt, decoder)
            .map_ok(|(name, region)| Country { name, region })
            .await
    }
}
```

Then, you can easily just decode a `Vec<Country>` from a binary `Stream` (there's no need to implement any `Visitor` for this because you can use the built-in implementation for `Vec<T: FromStream>`).

```rust
let countries = Vec::<Country>::from_stream(my_stream_of_byte_chunks).await?;
```

Does this resolve your issue?

**Comment by arnaudpoullet-dkt** [comment]
Not exactly, I have simplified my example with countries and a publicly available json that contains an array of objects. The actual json I'd like to deserialize is hundreds of MB big with enormous structs. That is why I would like to deserialize the big struct (which has nested fields), transform it into a smaller struct (by doing calculations and transformations and not just keeping less fields, or else I would just deserialize into the smaller struct immediately) and then take it into memory. This is to avoid taking up too much RAM and also to reduce the time before the application processes the first element while instead of waiting for the entire json to be taken into memory (it takes minutes!) it can process the elements one by one from the start.

Therefore I don't really see it easily done with `.map_ok(|(name, region, field3, field4, nested field?, field5, field6, ...)| Country { name, region, ... })`. Maybe a visitor has to be used after all ?

I thought it was to be combined with serde, my mistake ! Thank you for the explanation.


Right now when I'm trying to get a Stream with `&mut reqwest::get("https://restcountries.eu/rest/v2/all").await.unwrap().bytes_stream()`  I get following errors while both the reqwest crate & destream crate use `futures_core::Stream`. Is this expected ? If not I'll create a separate issue but I probably missed something.

```
error[E0277]: the trait bound `impl Stream: destream::Decoder` is not satisfied
   --> src/main.rs:49:55
    |
49  | ...::from_stream(() , &mut reqwest::get("https://restcountries.eu/rest/v2/all").await.unwrap().bytes_stream()).await.unwrap();
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `destream::Decoder` is not implemented for `impl Stream`
    | 
   ::: /home/arnaud/.cargo/registry/src/github.com-1ecc6299db9ec823/destream-0.3.2/src/de/mod.rs:187:14
    |
187 |     async fn from_stream<D: Decoder>(
    |              ----------- required by this bound in `from_stream`

error[E0277]: the trait bound `impl Stream: destream::Decoder` is not satisfied
  --> src/main.rs:49:22
   |
49 |     let countries  = Vec::<Country>::from_stream(() , &mut reqwest::get("https://restcountries.eu/rest/v2/all").await.unwrap().bytes_stre...
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `destream::Decoder` is not implemented for `impl Stream`


```

**Comment by haydnv** [comment]
This is actually pretty tricky since you don't have control over the format of the data you're decoding and you want to skip a lot of it. I added a generic `Value` type to destream_json in version 0.5.5 that you can use to decode and ignore the data that you don't care about. You can enable it using the "value" feature (`destream_json = { version = "~0.5.5", features = ["value"] }`). Here's a working example that includes decoding a nested field:

```rust
use std::collections::HashMap;

use async_trait::async_trait;
use destream::de::{Decoder, Error, FromStream, MapAccess, Visitor};
use destream_json::Value;

struct Language {
    name: String,
}

#[async_trait]
impl FromStream for Language {
    type Context = ();

    async fn from_stream<D: Decoder>(cxt: (), decoder: &mut D) -> Result<Self, D::Error> {
        let mut data = HashMap::<String, Value>::from_stream(cxt, decoder).await?;

        let name = match data.remove("name") {
            Some(Value::String(name)) => name,
            _ => return Err(Error::custom("invalid language name")),
        };

        Ok(Language { name })
    }
}

struct Country {
    name: String,
    region: String,
    languages: Vec<Language>,
}

#[async_trait]
impl FromStream for Country {
    type Context = ();

    async fn from_stream<D: Decoder>(_: (), decoder: &mut D) -> Result<Self, D::Error> {
        decoder.decode_map(CountryVisitor).await
    }
}

struct CountryVisitor;

#[async_trait]
impl Visitor for CountryVisitor {
    type Value = Country;

    fn expecting() -> &'static str {
        "a Country"
    }

    async fn visit_map<A: MapAccess>(self, mut map: A) -> Result<Country, A::Error> {
        let mut name: Option<String> = None;
        let mut region: Option<String> = None;
        let mut languages: Option<Vec<Language>> = None;

        while let Some(key) = map.next_key::<String>(()).await? {
            match key.as_str() {
                "name" => name = map.next_value(()).await?,
                "region" => region = map.next_value(()).await?,
                "languages" => languages = map.next_value(()).await?,
                _ => {
                    // you always need to call next_value after calling next_key, but you can ignore the result
                    map.next_value::<Value>(()).await?;
                }
            }
        }

        let name = name.ok_or_else(|| Error::custom("missing name"))?;
        let region = region.ok_or_else(|| Error::custom("missing region"))?;
        let languages = languages.ok_or_else(|| Error::custom("missing languages"))?;

        Ok(Country {
            name,
            region,
            languages,
        })
    }
}

#[tokio::main]
async fn main() {
    let data = reqwest::get("https://restcountries.eu/rest/v2/all")
        .await
        .unwrap()
        .bytes_stream();

    let countries: Vec<Country> = destream_json::try_decode((), data).await.unwrap();
    println!("first country name: {}", countries[0].name);
}
```

**Comment by arnaudpoullet-dkt** [comment]
Yes this compiles indeed !

This is a lot of work for simply going over an array of json objects, object per object ! At first I was mostly hoping, like the `csv_async` crate, to be able to send in an `AsyncRead` stream and get an Iterator back. The closest I have found until now is this blog_post/implementation [Efficient parsing of JSON record sets in Rust](https://dev.to/sergeyt/efficient-parsing-of-json-record-sets-in-rust-p53). But it takes `Read + Seek` and is not async, although it takes any `'serde::Deserialize' struct` so that' a plus.

I believe that's maybe work for a higher-level library one day, probably using destream behind the scenes? If I had the competence I would do it myself, but for now I'll have to do with these 2 options.

Thank you for the implemented example and for your time !

**Comment by haydnv** [comment]
You're welcome!
